app = "smartcoach-api-dev"
primary_region = "cdg"

[build]

[env]
  APP_ENV = "development"

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0